server.port=8081
spring.application.name=api-projeto

# 1. Configurações do Banco H2 (Modo Arquivo Seguro)
spring.datasource.url=jdbc:h2:file:./redesocialdb;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# 2. Configurações do JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# Mantém os dados entre reinicializações
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# 3. Liberação do H2 Console no Navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console