### TESTE 1: CRIAR RECEITA COM SUCESSO (Prova o 201 Created)
POST http://localhost:8081/api/receitas
Content-Type: application/json

{
    "titulo": "Bolo de Cenoura",
    "ingredientes": "Cenoura, Trigo, Ovos, Chocolate",
    "passoApasso": "Bata tudo e asse por 40 min",
    "autorId": 1
}

### TESTE 2: LISTAR RECEITAS (Prova o GET e o uso de DTO de Resposta)
GET http://localhost:8081/api/receitas

### TESTE 3: VALIDAÇÃO DE ERRO (Prova o @Valid - Título vazio não pode passar, deve dar 400)
POST http://localhost:8081/api/receitas
Content-Type: application/json

{
    "titulo": "",
    "ingredientes": "Cenoura",
    "passoApasso": "Asse",
    "autorId": 1
}

### TESTE 4: BUSCAR ID INEXISTENTE (Prova a sua lógica do 404 Not Found)
GET http://localhost:8081/api/receitas/999

### TESTE 5: DELETAR RECEITA (Prova o 204 No Content)
DELETE http://localhost:8081/api/receitas/1